name: DiscordCommand
main: de.project_minecraft.commandDiscord.CommandDiscord
version: ${version}
authors:
  - sir_melonchen
description: Ein Command der einen Discord-Link ausspuckt
commands:
  discord:
    description: Hauptbefehl
    aliases: [d]
command-completions:
  discord:
    executor: de.project_minecraft.commandDiscord.commands.discordCommand
    tab-completer: de.project_minecraft.commandDiscord.commands.discordCommandTabCompleter
permissions:
  discord.admin:
    description: Erlaubt das Bearbeiten der Konfiguration
    default: op