name: DiscordCommand
main: de.project_minecraft.commandDiscord.CommandDiscord
version: ${version}
authors:
  - sir_melonchen
description: Ein Command der einen Discord-Link ausspuckt
commands:
  discord:
    description: Discord Link
    aliases: [d]
command-completions:
  discord:
    executor: de.project_minecraft.commandDiscord.commands.discordCommand
    tab-completer: de.project_minecraft.commandDiscord.commands.discordCommandTabCompleter
permissions:
  discord.admin:
    description: Allows executing admin commands
    default: op